### ISSUE TITLE
Vue?

### ISSUE THREAD

**Issue by nosizejosh** [maka-io/maka-cli#50]
Are there plans to include scaffolding a meteor + vue project?

**Comment by maka-io** [comment]
Yes there is!  The only road block I have is I actually haven't even setup my first Vue app yet as I'm messing around with Preact at the moment and seeing if that would be good to hook in.

**Comment by maka-io** [comment]
After going through a Vue.js tutorial and seeing it in action I'm not sold on how it's so much better than Blaze.  The templating is the same old handlebars and the view controller is reminiscent of backbone.  I'm going to go ahead and say it's a "no" for now, just so I don't keep anyone hanging.

FWIW, I recently did a Blaze app because I needed something that didn't require so much thought and planning that using React (Reflux, etc.) entails and it stood up just like it should and runs great.
